### ISSUE TITLE
Incompatible with junit-jupiter-api@5.6.2

### ISSUE THREAD

**Issue by p-m-j** [sormuras/junit-platform-maven-plugin#39]
Downgraded to junit-jupiter-api@5.4.2 to match examples and things start working but on 5.6.2 I get

```bash
[ERROR] Failed to execute goal de.sormuras.junit:junit-platform-maven-plugin:1.0.0-M5:launch (injected-launch) on project sdk: Execution failed!: java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory: org.junit.platform.launcher.core.LauncherFactory -> [Help 1]
```

**Comment by sormuras** [comment]
Yeah, this `junit-platform-maven-plugin` only works with JUnit Platform 1.4.x and Jupiter 5.4.x or older.

I'm planning to fix this in the coming weeks/months by reducing the scope/feature set of this plugin.

**Comment by rustybox** [comment]
Additionally, thanks for your work!

**Comment by rmannibucau** [comment]
@rustybox think master solves that now, do you want to give a try?

**Comment by rustybox** [comment]
@rmannibucau - Added to my task list, might take a few days to give it a whirl but didn't want to just say nothing until then.

**Comment by rustybox** [comment]
Sorry for late reply, 

I tried with with junit-platform-maven-plugin @ 1.1.0 and junit-jupiter-api@5.6.2 and got the same error as previously, 1.1.0 with 5.4.2 still good.

I'm just assuming here that whatever commit resolved this went into the 1.1.0 release, perhaps I'm wrong and need to install a snapshot release to local repo?
